version: 2
executors:
  dbExecutor:
    docker:
      - image: postgres:9.4.1
        auth:
          username: hassan
          password: hassan

jobs:
  build:
    executor: dbExecutor
    step: echo hello
    docker:
      - image: circleci/node:14
      - image: postgres:9.4.1
        auth:
          username: hassan
          password: hassan
        environment:
          POSTGRES_USER: root
    steps:
      - checkout
      - run: |
          sudo -u root createuser -h localhost --superuser hassan &&
          sudo createdb -h localhost test_db