version: 2.1
jobs:
  build:
      docker:
      - image: circleci/node:7.10
        environment:
          PGHOST: 127.0.0.1
          PGUSER: rockchalkwushock
          NODE_ENV: test
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_DB: graphql_todo_test
          POSTGRES_PASSWORD: ""
          POSTGRES_USER: rockchalkwushock
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run test


