version: 2
executors:
  dbExecutor:
    docker:
      - image: postgres:9.4.1
        environment:
          POSTGRES_USER: postgres
    environment:
      NODE_ENV: test
      POSTGRES_USER: circleci
      POSTGRES_DB: circleci
      JWT_SECRET: sekrit

jobs:
  build:
    executor: dbExecutor
    step: echo hello
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: |
          sudo -u root createuser -h localhost --superuser hassan &&
          sudo createdb -h localhost test_db