version: 2
jobs:
  build:
    docker:
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: postgres
    environment:
      NODE_ENV: test
      POSTGRES_USER: circleci
      POSTGRES_PASSWORD: circleci
      POSTGRES_DB: circleci
      JWT_SECRET: sekrit
      TEST_DATABASE_URL: postgresql://circleci:circleci@localhost:5432/circleci
    steps:
      - checkout
      - run: sudo -u pg_ctl -D /usr/local/var/postgres start
      - run: createuser circleci --s && createdb circleci  --owner=circleci
      - run: npm install
      - run: npm run build:db
      - run: npm test