version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14

      - image: postgres:9.4.1
        auth:
          username: hassan
          password: hassan  # context / project UI env-var reference
        # some containers require setting environment variables
        environment:
          POSTGRES_USER: root

    environment:
      TEST_REPORTS: /tmp/test-reports

    working_directory: ~/my-project

    steps:
      - checkout
      - run: |
          sudo -u root createuser -h localhost --superuser hassan &&
          sudo createdb -h localhost test_db