version: 2
jobs:
  build:
    docker:
      - image: node:11.10.1
      - image: postgres:9.4.1
        environment:
          POSTGRES_USER: postgres
    environment:
      NODE_ENV: test
      POSTGRES_USER: circleci
      POSTGRES_DB: circleci
      JWT_SECRET: sekrit
    steps:
      - checkout
      - run: |
          sudo -u root createuser -h localhost --superuser hassan &&
          sudo createdb -h localhost test_db