version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
      
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: postgres

    environment:
      NODE_ENV: test
      POSTGRES_USER: circleci
      POSTGRES_PASSWORD: circleci
      POSTGRES_DB: circleci
      JWT_SECRET: sekrit
      TEST_DATABASE_URL: postgresql://circleci:circleci@localhost:5432/circleci
    steps:
      - checkout
      - run: psql -c "create database db_test;" -U postgres
      - run: psql -c "create user db1_project with password 'test';" -U postgres
      - run: npm install
      - run: npm run build:db
      - run: npm test

version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.8-jessie
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
      # CircleCI PostgreSQL images available at: https://hub.docker.com/r/circleci/postgres/
      - image: circleci/postgres:9.6-alpine
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          POSTGRES_USER: circleci-demo-go
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache

      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
        
      - run: psql -c "create database db_test;" -U postgres
      - run: psql -c "create user db1_project with password 'test';" -U postgres
      - run: npm install
      - run: npm run build:db
      - run: npm test
      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"

      - run:
          name: Start service
          environment:
            CONTACTS_DB_URL: "postgres://circleci-demo-go@localhost:5432/circle_test?sslmode=disable"
            CONTACTS_DB_MIGRATIONS: /go/src/github.com/CircleCI-Public/circleci-demo-go/db/migrations
          command: ./workdir/contacts
          background: true